name: Release on Tag
on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0
      - 'nightly-*'

permissions:
  contents: write

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        sudo apt-get install build-essential intltool libgtk-3-dev gcc g++  -y
    - name: Download YAD source
      run: |
        git clone https://github.com/v1cont/yad
    - name: Configure Make
      working-directory: ./yad
      run: |
        autoreconf -ivf && intltoolize
    - name: Make
      working-directory: ./yad/build
      run: |
        ../configure --enable-standalone && make -j16
    - name: Package project
      run: |
        zip --junk-paths yad ./yad/build/src/yad
    - name: Create Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags')
      with:
        draft: false
        prerelease: false
        files: ./yad.zip
