name: Release on Tag
on:
  push:
    branches:
      - master
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0
      - 'nightly-*'

permissions:
  contents: write

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        sudo apt-get install build-essential intltoolize libgtk-3-0-dev gcc g++  -y
    - name: Make
      run: |
        autoreconf -ivf && intltoolize
        mkdir build && cd build
        ../configure --enable-standalone && make
    - name: Package project
    # junk paths remove to recreate the path where is the file inside the zip package
      run: zip --junk-paths yad build/yad
    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags')
      with:
        draft: false
        prerelease: false
        files: yad.zip
